### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tflite-runtime (from versions: none)

### ISSUE THREAD

**Issue by malcouxen** [JuliaPoo/AsciiArtist#1]
ERROR: Could not find a version that satisfies the requirement tflite-runtime (from asciiartist) (from versions: none)
ERROR: No matching distribution found for tflite-runtime

**Comment by JuliaPoo** [comment]
Did you have anything else installed on your python environment? AsciiArtist allows all versions of `tflite-runtime`as long as it is compatible with every other dependency, which ive kept loose as well. Otherwise, it could just be your python version. `tflite-runtime` does not support the newer python versions if my memory serves me right.

**Comment by malcouxen** [comment]
would `3.9.2` work for this?

**Comment by JuliaPoo** [comment]
Ah that's a fairly new version, I'm certain `tflite-runtime` doesnt support 3.9 yet. To be sure, try `pip install tflite-runtime`

**Comment by malcouxen** [comment]
yeah that doesn't work. what python version do u recommend me

**Comment by JuliaPoo** [comment]
I'd recommend python 3.6 or 3.7
